version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
      - frontend_dist:/usr/share/nginx/html
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: ${FRONTEND_DOCKERFILE:-Dockerfile.dev}
    ports:
      - "3000:${FRONTEND_PORT:-3000}"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
      - NODE_ENV=${NODE_ENV:-development}
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ${FRONTEND_COMMAND:-npm run dev}

  backend:
    build:
      context: .
      dockerfile: backend/${BACKEND_DOCKERFILE:-Dockerfile.dev}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/kollab
      - DEBUG=${DEBUG:-1}
      - SECRET_KEY=${SECRET_KEY:-django-insecure-local-development-key}
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,backend
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - ./backend:/app/backend
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=kollab
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    name: kollab_postgres_data
  frontend_dist:
    name: kollab_frontend_dist
