# Generated by Django 5.1.7 on 2025-04-21 19:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('industry', models.CharField(choices=[('fashion', 'Fashion'), ('beauty', 'Beauty'), ('technology', 'Technology'), ('food', 'Food & Beverage'), ('health', 'Health & Wellness'), ('travel', 'Travel & Hospitality'), ('automotive', 'Automotive'), ('finance', 'Finance'), ('education', 'Education'), ('other', 'Other')], default='other', max_length=50)),
                ('company_size', models.CharField(choices=[('small', '1-50 employees'), ('medium', '51-500 employees'), ('large', '501-1000 employees'), ('enterprise', '1000+ employees')], default='small', max_length=50)),
                ('min_campaign_budget', models.DecimalField(decimal_places=2, default=0, help_text='Minimum budget for campaigns', max_digits=10)),
                ('max_campaign_budget', models.DecimalField(decimal_places=2, default=0, help_text='Maximum budget for campaigns', max_digits=10)),
                ('target_audience_age', models.CharField(blank=True, help_text='Target age range (e.g., 18-24, 25-34)', max_length=255)),
                ('target_audience_gender', models.CharField(blank=True, help_text='Target gender', max_length=255)),
                ('target_audience_location', models.CharField(blank=True, help_text='Target locations', max_length=255)),
                ('preferred_content_types', models.CharField(blank=True, help_text='Preferred types of content (e.g., photos, videos, stories)', max_length=255)),
                ('preferred_platforms', models.CharField(blank=True, help_text='Preferred social media platforms', max_length=255)),
                ('website', models.URLField(blank=True)),
                ('company_description', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'brands',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('niche', models.CharField(choices=[('fashion', 'Fashion'), ('beauty', 'Beauty'), ('lifestyle', 'Lifestyle'), ('fitness', 'Fitness'), ('food', 'Food'), ('travel', 'Travel'), ('tech', 'Technology'), ('gaming', 'Gaming'), ('parenting', 'Parenting'), ('business', 'Business'), ('education', 'Education'), ('other', 'Other')], default='other', max_length=50)),
                ('content_type', models.CharField(help_text='Type of content you create (e.g., photos, videos, blogs)', max_length=255)),
                ('instagram_followers', models.PositiveIntegerField(default=0)),
                ('youtube_subscribers', models.PositiveIntegerField(default=0)),
                ('tiktok_followers', models.PositiveIntegerField(default=0)),
                ('twitter_followers', models.PositiveIntegerField(default=0)),
                ('facebook_followers', models.PositiveIntegerField(default=0)),
                ('average_engagement_rate', models.FloatField(help_text='Average engagement rate across platforms', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('preferred_platforms', models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest')], help_text='Platforms you prefer to work with', max_length=255)),
                ('min_campaign_budget', models.DecimalField(decimal_places=2, default=0, help_text='Minimum budget for campaigns', max_digits=10)),
                ('max_campaign_budget', models.DecimalField(decimal_places=2, default=0, help_text='Maximum budget for campaigns', max_digits=10)),
                ('languages', models.CharField(blank=True, help_text='Languages you can create content in', max_length=255)),
                ('location', models.CharField(blank=True, help_text='Primary location for content creation', max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Influencer',
                'verbose_name_plural': 'Influencers',
                'db_table': 'influencers',
                'ordering': ('-created_at',),
            },
        ),
    ]
