# Generated by Django 5.1.7 on 2025-04-25 20:23

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('db', '0002_brand_influencer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='website',
            new_name='company_website',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='preferred_content_types',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='preferred_platforms',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='target_audience_age',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='target_audience_gender',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='target_audience_location',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='average_engagement_rate',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='facebook_followers',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='instagram_followers',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='tiktok_followers',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='twitter_followers',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='youtube_subscribers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='about',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='github',
        ),
        migrations.RemoveField(
            model_name='user',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_onboarded',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_password_autoset',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_password_expired',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mastodon',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_timezone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='website',
        ),
        migrations.AddField(
            model_name='influencer',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='target_demographic',
            field=models.JSONField(default=dict, help_text='Target audience demographics'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='tiktok_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='website_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='max_campaign_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='brand',
            name='min_campaign_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='content_type',
            field=models.CharField(choices=[('photos', 'Photos'), ('videos', 'Videos'), ('blogs', 'Blogs'), ('mixed', 'Mixed Content')], default='mixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='max_campaign_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='min_campaign_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='preferred_platforms',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn')], help_text='Primary platform for content creation', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
